### ISSUE TITLE
Time Tracking not working in Mantis V1.3.4

### ISSUE THREAD

**Issue by ninjakitteh69** [mantisbt-plugins/timetracking#18]
Hi

I'm in the process of upgrading mantis to the latest version and this plugin does not work on the latest version. (1.3.4)
I'm currently getting a outdated dependency for MantisBT Core 1.2.0.
is there any plan to update the plugin in the future?

Kind Regards

**Comment by dregad** [comment]
This plugin is community-supported (not very actively, as you can see), so unless you or someone else is willing to submit a pull request to adapt it to 1.3, it's unlikely to happen.

As a side note, 1.3.4 suffers from several regression issues, I suggest you either target 1.3.3 or wait for 1.3.5.

**Comment by cybosoft** [comment]
Not working for MantisBT2.0.0 either

**Comment by epenet** [comment]
v2 available: PR#19

**Comment by epenet** [comment]
v2 merged in: PR #21

**Comment by epenet** [comment]
@ninjakitteh69 I am not planning to make any changes to the plugin for Mantis v1.3.
However, I will happily take in Pull Requests on the corresponding branch https://github.com/mantisbt-plugins/timetracking/tree/master-1.0

**Comment by epenet** [comment]
@ninjakitteh69 I attempted to implement it in this branch, but I don't have a 1.3 setup to test against.
https://github.com/mantisbt-plugins/timetracking/tree/patch-db_query_bound

If you are able to test it, then I will pull it back into the master-1.0 branch.

**Comment by cproensa** [comment]
@ninjakitteh69 
branch for version 1.1 has been created which works in mantis v1.3
