### ISSUE TITLE
Differences in the sum of time

### ISSUE THREAD

**Issue by didaquis** [mantisbt-plugins/timetracking#23]
When viewing the result of the time summation in the page "view.php" is shown different from the result of the page "page = TimeTracking / show_report".

![image](https://cloud.githubusercontent.com/assets/6883041/25283631/b44a9ac0-26b4-11e7-8533-de918f4f9680.png)

![image](https://cloud.githubusercontent.com/assets/6883041/25283675/d88b334a-26b4-11e7-96b4-ee0285d8df68.png)

**Comment by epenet** [comment]
Did you select the correct "time frame"?
I see that 6:19 corresponds to the time spent in April, and 6:45 corresponds to March+April

**Comment by didaquis** [comment]
Yes, I select all the year!

**Comment by epenet** [comment]
Hi @didaquis,

I have tested this on my system, and I don't have the problem.
One thing for sure: the total at the top should be 6:43, not 6:45. This has been fixed in 2.0.5.

Below a screenshot from my system...

![image](https://cloud.githubusercontent.com/assets/6771947/25316492/75749b60-2868-11e7-99d1-ac003f46b182.png)

**Comment by didaquis** [comment]
HI @epenet I tested again this morning in other ticket.

I'm using MantisBt 2.3.0 and Time Tracking 2.0.4.

I introduced this register on ticket with id "76".
![lista_2](https://cloud.githubusercontent.com/assets/6883041/25326141/1917cd26-28cf-11e7-99d7-74e85a7d9c43.JPG)

I selected this range of dates:
![rango_2](https://cloud.githubusercontent.com/assets/6883041/25326159/398db9f8-28cf-11e7-89d4-5d82751a1b41.JPG)

And then, I obtain this results:
![dedicacion_2](https://cloud.githubusercontent.com/assets/6883041/25326169/4b50b6a4-28cf-11e7-8b40-2efda22cf911.JPG)

Maybe I'm doing something wrong? Any suggestion? Thank you for your help!

**Comment by epenet** [comment]
I see that "Filtros" format has changed in MantisBt 2.3.0. It is now a single field (previously was 3 fields for day/month/year). I assume this is linked...

I will try to upgrade my setup to 2.3.0 this week

**Comment by dregad** [comment]
Don't bother. This was reverted in 2.3.1 as it was introducing regressions. Note that this change will come back at some point, after more careful testing.

**Comment by epenet** [comment]
Thanks @dregad 

@didaquis, can you please upgrade to 2.3.1 and 2.0.5, then try again?

**Comment by dregad** [comment]
As a side note, if you're still on 2.3.0, you should **upgrade immediately** - see https://mantisbt.org/bugs/view.php?id=22739

**Comment by didaquis** [comment]
@epenet For sure, just give me some time. I need solve other questions first.

@dregad Thank you. I already patched this installation.

**Comment by didaquis** [comment]
@epenet Confirmed, the issue is solved using MantisBT 2.3.2 and TimeTRacking 2.0.5

Thanks!
