### ISSUE TITLE
Category dropdown does not have any options

### ISSUE THREAD

**Issue by HarpeyMark** [mantisbt-plugins/timetracking#28]
Just installed the plugin and the select box for category does not contain any options. Is there something else I have to do to setup categories?

[screenshot](https://i.imgtc.com/6w1qcdn.png)

**Comment by epenet** [comment]
@HarpeyMark 
You will need to go to the plugin configuration page, and set your categories in the corresponding textbox (one category per line).

1. Administration
2. Manage plugins
3. Time Tracking
4. Categories

**Comment by HarpeyMark** [comment]
Thank you.
