### ISSUE TITLE
css on "add" button 

### ISSUE THREAD

**Issue by fhaut** [mantisbt-plugins/timetracking#30]
Apply css on "Add button" to apply the standard mantis 2.0 web interface.

on TimeTracking.php, line 156 

who is : 

`     <td><input name="<?php echo plugin_lang_get( 'submit' ) ?>" type="submit" value="<?php echo plugin_lang_get( 'submit' ) ?>" /></td>
`

change to: 

`     <td><input class="btn btn-primary btn-sm btn-white btn-round" name="<?php echo plugin_lang_get( 'submit' ) ?>" type="submit" value="<?php echo plugin_lang_get( 'submit' ) ?>" /></td>
`

**Comment by dregad** [comment]
Next time, please submit your patch as a pull request instead, it will make things a lot easier. Thanks for your contribution, and your understanding.
